export const GAME_BALANCE = {
  durationSeconds: 90,
  comboWindowMs: 4300,
  baseComboMultiplier: 1,
  maxComboMultiplier: 8,
  bestiaModeComboThreshold: 4,
  bestiaModeDurationMs: 9000,
  bestiaModeScoreMultiplier: 1.75,
  bestiaModeSpeedMultiplier: 1.18,
  policeTurnLockDurationMs: 5000,
  difficulty: {
    mediumAfterSeconds: 28,
    chaosAfterSeconds: 64,
  },
  start: {
    countdownStepMs: 760,
    sequence: ["3", "2", "1", "YA"],
  },
  effects: {
    impactFlashMs: 110,
    normalShakeDurationMs: 130,
    normalShakeIntensity: 0.008,
    highComboShakeDurationMs: 180,
    highComboShakeIntensity: 0.012,
    policeShakeDurationMs: 220,
    policeShakeIntensity: 0.014,
    floatingTextDurationMs: 1050,
    highComboThreshold: 4,
  },
  missions: {
    destroyCars: {
      label: "Romper 8 autos",
      target: 8,
      bonus: 600,
    },
    comboStreak: {
      label: "Combo x4",
      target: 4,
      bonus: 800,
    },
    bestiaMode: {
      label: "Bestia Mode",
      target: 1,
      bonus: 800,
    },
  },
  score: {
    normalCar: 110,
    taxi: 130,
    van: 160,
    policeCar: 230,
  },
  player: {
    baseSpeed: 395,
    spriteScale: 0.42,
    width: 250,
    height: 430,
    minX: 210,
    maxX: 510,
  },
  riders: {
    spawnMinMs: 9000,
    spawnMaxMs: 15000,
    speed: 220,
    spriteHeight: 96,
    basePoints: 250,
    scoreMultiplier: 2,
    colliderWidthRatio: 0.72,
    colliderHeightRatio: 0.82,
    colliderOffsetXRatio: 0.14,
    colliderOffsetYRatio: 0.09,
  },
  traffic: {
    carWidth: 74,
    carHeight: 138,
    vanWidth: 88,
    vanHeight: 154,
    firstSpawnDelayMs: 650,
    colliderWidthRatio: 0.72,
    colliderHeightRatio: 0.9,
    colliderOffsetXRatio: 0.14,
    colliderOffsetYRatio: 0.05,
    explosionSize: 116,
    lanes: [258, 360, 466],
    easy: {
      spawnEveryMs: 980,
      minSpeed: 170,
      maxSpeed: 235,
      policeChance: 0,
    },
    medium: {
      spawnEveryMs: 670,
      minSpeed: 230,
      maxSpeed: 325,
      policeChance: 0.1,
    },
    chaos: {
      spawnEveryMs: 470,
      minSpeed: 320,
      maxSpeed: 445,
      policeChance: 0.2,
    },
  },
} as const;

export type DifficultyLevel = "easy" | "medium" | "chaos";
