import type { CarModel } from "../types";

export const GAME_BALANCE = {
  durationSeconds: 90,
  policeTurnLockDurationMs: 5000,
  difficulty: {
    mediumAfterSeconds: 25,
    chaosAfterSeconds: 60,
  },
  start: {
    countdownStepMs: 760,
    sequence: ["3", "2", "1", "YA"],
  },
  effects: {
    impactFlashMs: 110,
    normalShakeDurationMs: 130,
    normalShakeIntensity: 0.008,
    policeShakeDurationMs: 220,
    policeShakeIntensity: 0.014,
    floatingTextDurationMs: 1050,
  },
  score: {
    peugeot: 80,
    chery: 100,
    meriva: 180,
    focus: 140,
    eco: 120,
  } satisfies Record<CarModel, number>,
  missionScoring: {
    completionMultiplier: 10,
    missions: [
      { id: "meriva-combo-x4", label: "MERIVA COMBO x4", model: "meriva", target: 4 },
      { id: "chery-combo-x5", label: "CHERY COMBO x5", model: "chery", target: 5 },
      { id: "focus-combo-x3", label: "FOCUS COMBO x3", model: "focus", target: 3 },
      { id: "eco-combo-x3", label: "ECO COMBO x3", model: "eco", target: 3 },
      { id: "peugeot-combo-x4", label: "PEUGEOT COMBO x4", model: "peugeot", target: 4 },
    ],
  },
  player: {
    baseSpeed: 395,
    spriteScale: 0.42,
    width: 190,
    height: 430,
    minX: 210,
    maxX: 510,
  },
  traffic: {
    carWidth: 74,
    vanWidth: 88,
    carHeight: 138,
    vanHeight: 154,
    firstSpawnDelayMs: 650,
    colliderWidthRatio: 0.72,
    colliderHeightRatio: 0.9,
    colliderOffsetXRatio: 0.14,
    colliderOffsetYRatio: 0.05,
    explosionSize: 116,
    minVehicleGap: 190,
    safePassageWindowPx: 220,
    maxBlockedLanesInWindow: 2,
    spawnSkipIfNoSafeLane: true,
    focusSpeedMultiplier: 1.28,
    lanes: [258, 360, 462],
    easy: {
      spawnEveryMs: 920,
      minSpeed: 160,
      maxSpeed: 225,
      policeChance: 0.03,
      modelWeights: {
        peugeot: 34,
        chery: 28,
        meriva: 12,
        focus: 16,
        eco: 10,
      },
    },
    medium: {
      spawnEveryMs: 640,
      minSpeed: 225,
      maxSpeed: 330,
      policeChance: 0.1,
      modelWeights: {
        peugeot: 28,
        chery: 26,
        meriva: 16,
        focus: 18,
        eco: 12,
      },
    },
    chaos: {
      spawnEveryMs: 430,
      minSpeed: 315,
      maxSpeed: 455,
      policeChance: 0.18,
      modelWeights: {
        peugeot: 22,
        chery: 24,
        meriva: 18,
        focus: 22,
        eco: 14,
      },
    },
  },
  streetEvents: {
    womanScale: 0.082,
    womanMinY: 300,
    womanMaxY: 760,
    womanLeftX: 175,
    womanRightX: 545,
    womanMinIntervalMs: 10000,
    womanMaxIntervalMs: 15000,
    dialogMs: 1650,
  },
} as const;

export type DifficultyLevel = "easy" | "medium" | "chaos";
