export const GAME_BALANCE = {
  durationSeconds: 90,
  comboWindowMs: 4300,
  baseComboMultiplier: 1,
  maxComboMultiplier: 8,
  bestiaModeComboThreshold: 4,
  bestiaModeDurationMs: 6000,
  bestiaModeMaxDurationMs: 10000,
  bestiaModeHitExtendMs: 400,
  bestiaModeScoreMultiplier: 2,
  bestiaModeSpeedMultiplier: 1.18,
  bestiaChargeMax: 100,
  bestiaCharge: {
    ecoHit: 28,
    sequenceCombo: 32,
  },
  policeTurnLockDurationMs: 5000,
  difficulty: {
    mediumAfterSeconds: 25,
    chaosAfterSeconds: 60,
  },
  start: {
    countdownStepMs: 760,
    sequence: ["3", "2", "1", "YA"],
  },
  effects: {
    impactFlashMs: 110,
    normalShakeDurationMs: 130,
    normalShakeIntensity: 0.008,
    highComboShakeDurationMs: 180,
    highComboShakeIntensity: 0.012,
    policeShakeDurationMs: 220,
    policeShakeIntensity: 0.014,
    floatingTextDurationMs: 1050,
    highComboThreshold: 4,
  },
  missions: {
    destroyCars: {
      label: "Romper 8 autos",
      target: 8,
      bonus: 600,
    },
    comboStreak: {
      label: "Combo x4",
      target: 4,
      bonus: 800,
    },
    bestiaMode: {
      label: "Bestia Mode",
      target: 1,
      bonus: 800,
    },
  },
  flashMissions: {
    firstAtSeconds: 12,
    intervalMs: 14500,
    durationMs: 11000,
    bestiaCharge: 16,
    list: [
      { id: "flashChery", label: "Rompe 3 Chery", target: 3, bonus: 900 },
      { id: "flashFocusEco", label: "Rompe Focus + Eco", target: 2, bonus: 1000 },
      { id: "flashPoliceBestia", label: "Policia en Bestia", target: 1, bonus: 1400 },
      { id: "flashRappiCars", label: "Rappi + 5 autos", target: 5, bonus: 1200 },
      { id: "flashCallejero", label: "Combo Callejero", target: 1, bonus: 1500 },
    ],
  },
  score: {
    peugeot: 80,
    chery: 100,
    meriva: 180,
    focus: 140,
    eco: 120,
    normalCar: 100,
    taxi: 130,
    van: 160,
    policeCar: 250,
    policeBestia: 1000,
  },
  sequenceCombos: [
    { models: ["chery", "chery", "chery"], bonus: 600, label: "Combo Chery" },
    { models: ["focus", "focus", "focus"], bonus: 700, label: "Combo Velocidad" },
    { models: ["meriva", "eco"], bonus: 500, label: "Combo Pesado" },
    { models: ["peugeot", "chery", "focus"], bonus: 900, label: "Combo Callejero" },
    { models: ["chery", "meriva", "eco"], bonus: 1200, label: "Combo Bestia" },
  ],
  modelBonuses: {
    cheryStreak: 600,
    merivaCombo: 350,
    focusEarly: 300,
  },
  player: {
    baseSpeed: 395,
    spriteScale: 0.42,
    width: 190,
    height: 430,
    minX: 210,
    maxX: 510,
  },
  riders: {
    spawnMinMs: 13000,
    spawnMaxMs: 21000,
    speed: 220,
    spriteHeight: 96,
    rappiMultiplier: 2,
    rappiDurationMs: 8000,
    pedidosYaBonusMultiplier: 1.5,
    pedidosYaDurationMs: 8000,
    colliderWidthRatio: 0.56,
    colliderHeightRatio: 0.82,
    colliderOffsetXRatio: 0.14,
    colliderOffsetYRatio: 0.09,
  },
  traffic: {
    carWidth: 74,
    carHeight: 138,
    vanWidth: 88,
    vanHeight: 154,
    firstSpawnDelayMs: 650,
    colliderWidthRatio: 0.72,
    colliderHeightRatio: 0.9,
    colliderOffsetXRatio: 0.14,
    colliderOffsetYRatio: 0.05,
    explosionSize: 116,
    minVehicleGap: 190,
    focusSpeedMultiplier: 1.28,
    lanes: [258, 360, 462],
    easy: {
      spawnEveryMs: 920,
      minSpeed: 160,
      maxSpeed: 225,
      policeChance: 0.03,
      modelWeights: {
        peugeot: 34,
        chery: 28,
        meriva: 12,
        focus: 16,
        eco: 10,
      },
    },
    medium: {
      spawnEveryMs: 640,
      minSpeed: 225,
      maxSpeed: 330,
      policeChance: 0.1,
      modelWeights: {
        peugeot: 28,
        chery: 26,
        meriva: 16,
        focus: 18,
        eco: 12,
      },
    },
    chaos: {
      spawnEveryMs: 430,
      minSpeed: 315,
      maxSpeed: 455,
      policeChance: 0.18,
      modelWeights: {
        peugeot: 22,
        chery: 24,
        meriva: 18,
        focus: 22,
        eco: 14,
      },
    },
  },
  streetEvents: {
    womanScale: 0.082,
    womanMinY: 300,
    womanMaxY: 760,
    womanLeftX: 175,
    womanRightX: 545,
    dialogMs: 1650,
  },
} as const;

export type DifficultyLevel = "easy" | "medium" | "chaos";
